# Dockerfile pour le Frontend (Apache)

# Étape 1: Utilisation de l'image officielle Apache
FROM httpd:latest

# Étape 2: Copier les fichiers du frontend dans le répertoire d'Apache
COPY ./ /usr/local/apache2/htdocs/

# Étape 3: Exposer le port 8080
EXPOSE 8080
